### ISSUE TITLE
VirusTotal flags the Fatpack as a virus

### ISSUE THREAD

**Issue by fotisandstuff** [theChaosCoder/vapoursynth-portable-FATPACK#7]
Hello! I downloaded the Fatpack from here as a .zip and uploaded it to [VirusTotal](https://www.virustotal.com/gui/home/upload). Unfortunately, one out of the 56 vendors marks it as a virus. Could you please look into this? Thanks!

**Comment by theChaosCoder** [comment]
It's a false positive.
There's not much I can do about it.

If you scan the offical VapourSynth installer, you'll notice that it also gets flaged as "virus" by one vendor.

https://www.virustotal.com/gui/file/b13e9a20e698acea881efbc2cdd2b6473a1448b293fbb2899908bfd77901d0d7

Funny thing, my release was clean https://www.virustotal.com/gui/file/8f74c42ab675abaa011a7b8bd4df22aa9da5bff2fda44902324ce655acca5701?nocache=1

Probaly because some scanners had a timeout....
